name: Periodic health check

on:
  schedule:
    - cron: '0 0 1 1 *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-lj8u.onrender.com/health
          max-attempts: 3
          retry-delay: 15s
      
      - name: Success
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} healthcheck was successful.'

      - name: Failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Healthcheck for {{ EVENT_PAYLOAD.repository.full_name }} has failed.'